# Generated by Django 4.0.1 on 2022-01-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile', verbose_name='الضوره الشخصيه:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='الاسم :'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(null=True, verbose_name=':سعر الكشف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(max_length=250, null=True, verbose_name='من انا:'),
        ),
    ]
