# Generated by Django 4.0.1 on 2022-01-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='المحافطه:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_details',
            field=models.CharField(max_length=50, null=True, verbose_name='العنوان بالتفاصيل:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.IntegerField(null=True, verbose_name='الهاتف:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist_doctor',
            field=models.CharField(max_length=50, null=True, verbose_name='متخصص في ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(max_length=50, null=True, verbose_name='نبذه عنك:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(null=True, verbose_name='مده الانتظار:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default=1, max_length=50, verbose_name='عدد ساعات العمل:'),
            preserve_default=False,
        ),
    ]
