# Generated by Django 4.0.1 on 2022-01-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_address_profile_address_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(choices=[('ختصاص أمراض الأطفال', 'ختصاص أمراض الأطفال'), ('الصدر والجهاز التنفسي', 'الصدر والجهاز التنفسي'), ('طب الأشعة', 'طب الأشعة'), ('الأنف والأذن والحنجرة', 'الأنف والأذن والحنجرة'), ('طب الأعصاب وجراحتها', 'طب الأعصاب وجراحتها'), ('الطب النفسي', 'الطب النفسي'), (' الجراحة التجميلية', ' الجراحة التجميلية'), ('طب الأعصاب وجراحتها', 'طب الأعصاب وجراحتها')], max_length=50, null=True),
        ),
    ]
