# Generated by Django 4.0.1 on 2022-01-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='patient_email',
            field=models.CharField(max_length=50, null=True, verbose_name='حساب المريض:'),
        ),
    ]
