# Generated by Django 4.0.1 on 2022-01-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_order_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(choices=[('الإسكندرية', 'الإسكندرية'), ('أسوان', 'أسوان'), ('الدقهلية', 'الدقهلية'), ('الغربية', 'الغربية'), ('القاهرة', 'القاهرة'), ('مطروح', 'مطروح')], max_length=50, null=True, verbose_name='المحافطه:'),
        ),
    ]
