# Generated by Django 4.0.1 on 2022-01-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_order_profile_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='الاسم :'),
        ),
    ]
