# Generated by Django 4.0.1 on 2022-01-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='name',
        ),
        migrations.AddField(
            model_name='rate',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='الايميل'),
        ),
    ]
