# Generated by Django 4.0.1 on 2022-01-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_rate_name_rate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='الايميل'),
        ),
    ]
