# Generated by Django 4.0.1 on 2022-01-20 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rate_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.order'),
        ),
    ]
