# Generated by Django 4.0.1 on 2022-01-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_rate_doctor_alter_rate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(null=True, verbose_name=':خطوط العرض'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lng',
            field=models.FloatField(null=True, verbose_name=':خطوظ الطول'),
        ),
    ]
