# Generated by Django 4.0.1 on 2022-01-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_lat_profile_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=0, null=True, verbose_name=':خطوط العرض'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lng',
            field=models.FloatField(default=0, null=True, verbose_name=':خطوظ الطول'),
        ),
    ]
